Repository bpm-crafters/process-engine-adapters-camunda-7, pull requests merged in 2025-05, with the labels that each got.

#35 deploy with duplicate filtering
  engine-adapter/c7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/deploy/DeploymentApiImpl.kt
Labels: Type: enhancement

#43 don't use empty string as a tenant
  engine-adapter/c7-embedded-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/deploy/DeploymentApiImpl.kt
  engine-adapter/c7-embedded-core/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/deploy/DeploymentApiImplTest.kt
  engine-adapter/c7-embedded-core/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/embedded/process/C7EmbeddedStartProcessApiITest.kt
Labels: Type: bug, Type: breaking

#51 serialize null dates as empty string
  engine-adapter/c7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/TaskInformationExtensions.kt
  engine-adapter/c7-remote-core/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/delivery/TaskInformationExtensionsKtTest.kt
Labels: Prio: MUST, Type: bug

#53 Allow to disable the delivery strategy for service tasks
  engine-adapter/c7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/completion/NoOpServiceTaskCompletionApiImpl.kt
  engine-adapter/c7-remote-core/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/task/completion/NoOpUserTaskCompletionApiImpl.kt
  engine-adapter/c7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteAdapterAutoConfiguration.kt
  engine-adapter/c7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteNoOpConfiguration.kt
  engine-adapter/c7-remote-spring-boot-starter/src/main/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemotePullServicesAutoConfiguration.kt
  engine-adapter/c7-remote-spring-boot-starter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  engine-adapter/c7-remote-spring-boot-starter/src/test/kotlin/dev/bpmcrafters/processengineapi/adapter/c7/remote/springboot/C7RemoteAdapterConditionsTest.kt
Labels: Prio: MUST, Type: bug
